// this file was generated by ./test/codegen/tbgen
// do NOT edit it by hand
module circuit_tb();
reg clk, reset;
reg [31:0] current_vec, error_count;
reg [3052:0] test_vectors [1023:0];
reg [1525:0] current;
reg [1525:0] next;
reg [0:0] exp_result;
wire [0:0] result;
circuit dut(
.current(current),
.next(next),
.result(result)
);
always
  begin
    clk = 1; #5; clk = 0; #5;
  end
initial
  begin
    $dumpfile("circuit.tb.vcd");
    $dumpvars(0, circuit_tb);
    $readmemb("out.e2e.tv", test_vectors);
    current_vec = 0; error_count = 0;
    reset = 1; #10; reset = 0;
  end
always @(posedge clk)
  begin
    #1; { current, next, exp_result } = test_vectors[current_vec];
  end
always @(negedge clk)
  begin
    if (~reset) begin
      if (exp_result === result || exp_result === 1'bx) begin
  $display("TBGEN-PASS circuit:%0d result", current_vec);
end else begin
  $display("TBGEN-FAIL circuit:%0d expected result to be 0x%h, was 0x%h", current_vec, exp_result, result);
  error_count = error_count + 1;
end

      current_vec = current_vec + 1;

      if (test_vectors[current_vec] === 3053'bx) begin
        $display("TBGEN-DONE circuit %0d errors=%0d", current_vec, error_count);
        $finish;
      end
    end
  end
endmodule
