/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.3. DO NOT MODIFY.
*/
module syscall
    ( // Inputs
      input [31:0] eax


      // Outputs
    , output wire  out
    );


  assign out = {1 {1'bx}};


endmodule

