/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module alu
    ( // Inputs
      input [17:0] cntl
    , input [6:0] status_in
    , input [31:0] opnd0_r
    , input [31:0] opnd1_r

      // Outputs
    , output wire [6:0] status_out
    , output wire [31:0] result
    );
  wire [31:0] result_2;
  wire  x;
  wire [6:0] result_3;
  wire  c$app_arg;
  wire  c$case_alt;
  wire  c$case_alt_0;
  wire  c$app_arg_0;
  wire  c$case_alt_1;
  reg [0:0] c$app_arg_1;
  wire  c$app_arg_2;
  wire  c$case_alt_2;
  wire [32:0] result_4;
  wire  c$app_arg_3;
  wire  c$case_alt_3;
  reg  result_5;
  wire  c$case_alt_4;
  wire  x_0;
  wire  c$app_arg_4;
  wire  c$case_alt_5;
  wire  c$app_arg_5;
  wire [32:0] c$app_arg_6;
  wire  c$app_arg_7;
  wire [31:0] c$app_arg_8;
  wire  c$app_arg_9;
  wire [31:0] c$app_arg_10;
  wire  c$app_arg_11;
  wire [6:0] c$app_arg_12;
  wire  result_6;
  wire  x_1;
  wire [17:0] c$x_app_arg;
  wire [32:0] result_7;
  wire  carry;
  wire [32:0] result_8;
  wire [32:0] c$case_alt_6;
  wire [32:0] c$case_alt_7;
  wire [32:0] c$case_alt_8;
  wire [32:0] c$case_alt_9;
  wire [31:0] c$app_arg_13;
  wire [32:0] c$case_alt_10;
  wire [32:0] c$case_alt_11;
  wire [32:0] c$case_alt_12;
  wire [32:0] c$case_alt_13;
  wire [32:0] c$case_alt_14;
  wire [32:0] c$case_alt_15;
  wire [32:0] c$case_alt_16;
  wire [31:0] c$app_arg_14;
  wire [32:0] c$case_alt_17;
  wire [31:0] c$app_arg_15;
  wire signed [63:0] wild;
  wire signed [63:0] c$wild_app_arg;
  wire  c$app_arg_16;
  wire  c$app_arg_17;
  wire  c$app_arg_18;
  wire  c$app_arg_19;
  wire  c$app_arg_20;
  wire  c$app_arg_21;
  wire  c$app_arg_22;
  wire  c$app_arg_23;
  wire  c$app_arg_24;
  wire  c$app_arg_25;
  wire  c$app_arg_26;
  wire [17:0] lvl3;
  wire  c$eta_app_arg;
  wire [6:0] c$eta_app_arg_0;
  wire [6:0] status_in_0;
  wire  c$eta_app_arg_1;
  wire [17:0] c$eta_app_arg_2;
  wire [17:0] cntl_0;
  wire [31:0] opnd1_r_0;
  wire [31:0] opnd0_r_0;
  wire [88:0] c$arg;
  wire [31:0] result_sel_alt_t_res;
  wire [31:0] c$vec;
  wire [32:0] c$bv;
  wire [0:0] result_selection_res;
  wire [63:0] c$bv_0;
  wire [38:0] result_0;

  assign c$arg = {cntl,   status_in,   opnd0_r,
                  opnd1_r};

  assign result_0 = {result_3,   result_2};

  assign c$vec = (32'b00000000000000000000000000000000);

  // map begin
  genvar i;
  generate
  for (i=0; i < 32; i = i + 1) begin : map
    wire [0:0] map_in;
    assign map_in = c$vec[i*1+:1];
    wire  map_out;
    assign map_out = map_in;


    assign result_sel_alt_t_res[i*1+:1] = map_out;
  end
  endgenerate
  // map end

  assign result_2 = (((x)) == 1'b1) ? result_sel_alt_t_res : (result_7[32-1 : 0]);

  assign x = c$eta_app_arg_2[8:8];

  assign result_3 = {c$app_arg_11,   c$app_arg_4,
                     c$app_arg_3,   c$app_arg_2,   c$app_arg_0,
                     c$app_arg,   1'b0};

  assign c$app_arg = result_6 ? c$case_alt : c$case_alt_0;

  assign c$case_alt = c$app_arg_12[5:5];

  assign c$case_alt_0 = result_7[31:31];

  assign c$app_arg_0 = result_6 ? c$case_alt_1 : ((c$app_arg_1));

  assign c$case_alt_1 = c$app_arg_12[4:4];

  always @(*) begin
    case(result_4)
      33'b000000000000000000000000000000000 : c$app_arg_1 = 1'b1;
      default : c$app_arg_1 = 1'b0;
    endcase
  end

  assign c$bv = (result_4);

  assign c$app_arg_2 = result_6 ? c$case_alt_2 : (~ (^ (((c$bv[7 : 0])))));

  assign c$case_alt_2 = c$app_arg_12[3:3];

  assign result_4 = ((result_7));

  assign c$app_arg_3 = result_6 ? c$case_alt_3 : result_5;

  assign c$case_alt_3 = c$app_arg_12[2:2];

  assign result_selection_res = (x_0);

  always @(*) begin
    case(result_selection_res)
      1'b1 : result_5 = 1'b0;
      default : result_5 = c$case_alt_4;
    endcase
  end

  assign c$case_alt_4 = result_7[32:32];

  assign x_0 = c$x_app_arg[5:5];

  assign c$app_arg_4 = result_6 ? c$case_alt_5 : ((c$app_arg_9 ^ c$app_arg_7) ^ c$app_arg_5);

  assign c$case_alt_5 = c$app_arg_12[1:1];

  assign c$app_arg_5 = c$app_arg_6[28:28];

  // reverse begin
  genvar i_0;
  generate
  for (i_0 = 0; i_0 < 33; i_0 = i_0 + 1) begin : reverse
    assign c$app_arg_6[(33 - 1 - i_0)*1+:1] = result_7[i_0*1+:1];
  end
  endgenerate
  // reverse end

  assign c$app_arg_7 = c$app_arg_8[27:27];

  // reverse begin
  genvar i_1;
  generate
  for (i_1 = 0; i_1 < 32; i_1 = i_1 + 1) begin : reverse_0
    assign c$app_arg_8[(32 - 1 - i_1)*1+:1] = opnd1_r_0[i_1*1+:1];
  end
  endgenerate
  // reverse end

  assign c$app_arg_9 = c$app_arg_10[27:27];

  // reverse begin
  genvar i_2;
  generate
  for (i_2 = 0; i_2 < 32; i_2 = i_2 + 1) begin : reverse_1
    assign c$app_arg_10[(32 - 1 - i_2)*1+:1] = opnd0_r_0[i_2*1+:1];
  end
  endgenerate
  // reverse end

  assign c$app_arg_11 = c$app_arg_12[0:0];

  // reverse begin
  genvar i_3;
  generate
  for (i_3 = 0; i_3 < 7; i_3 = i_3 + 1) begin : reverse_2
    assign c$app_arg_12[(7 - 1 - i_3)*1+:1] = status_in_0[i_3*1+:1];
  end
  endgenerate
  // reverse end

  assign result_6 = ((x_1)) == 1'b1;

  assign x_1 = c$x_app_arg[6:6];

  // reverse begin
  genvar i_4;
  generate
  for (i_4 = 0; i_4 < 18; i_4 = i_4 + 1) begin : reverse_3
    assign c$x_app_arg[(18 - 1 - i_4)*1+:1] = cntl_0[i_4*1+:1];
  end
  endgenerate
  // reverse end

  assign result_7 = (result_8);

  assign carry = c$eta_app_arg_1 & c$eta_app_arg;

  assign result_8 = (1'b1 == c$app_arg_26) ? c$case_alt_6 : c$case_alt_7;

  assign c$case_alt_6 = (((opnd0_r_0))) + c$app_arg_13;

  assign c$case_alt_7 = (1'b1 == c$app_arg_25) ? c$case_alt_8 : c$case_alt_9;

  assign c$case_alt_8 = (((opnd0_r_0))) - c$app_arg_13;

  assign c$case_alt_9 = (1'b1 == c$app_arg_24) ? ({1'b0,((((opnd0_r_0))) & (((opnd1_r_0))))}) : c$case_alt_10;

  assign c$app_arg_13 = (((opnd1_r_0))) + ({31'b0000000000000000000000000000000,((carry))});

  assign c$case_alt_10 = (1'b1 == c$app_arg_23) ? ({1'b0,((((opnd0_r_0))) | (((opnd1_r_0))))}) : c$case_alt_11;

  assign c$case_alt_11 = (1'b1 == c$app_arg_22) ? ({1'b0,((((opnd0_r_0))) ^ (((opnd1_r_0))))}) : c$case_alt_12;

  assign c$case_alt_12 = (1'b1 == c$app_arg_21) ? ({1'b0,((((opnd0_r_0))) * (((opnd1_r_0))))}) : c$case_alt_13;

  assign c$case_alt_13 = (1'b1 == c$app_arg_20) ? ({1'b0,((((opnd0_r_0))) << wild)}) : c$case_alt_14;

  assign c$case_alt_14 = (1'b1 == c$app_arg_19) ? ({1'b0,((((opnd0_r_0))) >> wild)}) : c$case_alt_15;

  assign c$case_alt_15 = (1'b1 == c$app_arg_18) ? ({1'b0,c$app_arg_14}) : c$case_alt_16;

  assign c$case_alt_16 = (1'b1 == c$app_arg_17) ? ({1'b0,c$app_arg_15}) : c$case_alt_17;

  // rotateL begin
  wire [2*32-1:0] bv;
  assign bv = {(((opnd0_r_0))),(((opnd0_r_0)))} << (wild % 32);
  assign c$app_arg_14 = bv[2*32-1 : 32];
  // rotateL end

  assign c$case_alt_17 = (1'b1 == c$app_arg_16) ? ({1'b0,((((opnd0_r_0))) / (((opnd1_r_0))))}) : ({33 {1'bx}});

  // rotateR begin
  wire [2*32-1:0] bv_0;
  assign bv_0 = {(((opnd0_r_0))),(((opnd0_r_0)))} >> (wild % 32);
  assign c$app_arg_15 = bv_0[32-1 : 0];
  // rotateR end

  assign wild = $signed(c$wild_app_arg);

  assign c$bv_0 = ({32'b00000000000000000000000000000000,(((opnd1_r_0)))});

  assign c$wild_app_arg = $unsigned(c$bv_0[0+:64]);

  assign c$app_arg_16 = lvl3[11:11];

  assign c$app_arg_17 = lvl3[0:0];

  assign c$app_arg_18 = lvl3[1:1];

  assign c$app_arg_19 = lvl3[2:2];

  assign c$app_arg_20 = lvl3[3:3];

  assign c$app_arg_21 = lvl3[12:12];

  assign c$app_arg_22 = lvl3[13:13];

  assign c$app_arg_23 = lvl3[14:14];

  assign c$app_arg_24 = lvl3[15:15];

  assign c$app_arg_25 = lvl3[7:7];

  assign c$app_arg_26 = lvl3[16:16];

  // reverse begin
  genvar i_5;
  generate
  for (i_5 = 0; i_5 < 18; i_5 = i_5 + 1) begin : reverse_4
    assign lvl3[(18 - 1 - i_5)*1+:1] = cntl_0[i_5*1+:1];
  end
  endgenerate
  // reverse end

  assign c$eta_app_arg = c$eta_app_arg_0[2:2];

  // reverse begin
  genvar i_6;
  generate
  for (i_6 = 0; i_6 < 7; i_6 = i_6 + 1) begin : reverse_5
    assign c$eta_app_arg_0[(7 - 1 - i_6)*1+:1] = status_in_0[i_6*1+:1];
  end
  endgenerate
  // reverse end

  assign status_in_0 = c$arg[70:64];

  assign c$eta_app_arg_1 = c$eta_app_arg_2[10:10];

  // reverse begin
  genvar i_7;
  generate
  for (i_7 = 0; i_7 < 18; i_7 = i_7 + 1) begin : reverse_6
    assign c$eta_app_arg_2[(18 - 1 - i_7)*1+:1] = cntl_0[i_7*1+:1];
  end
  endgenerate
  // reverse end

  assign cntl_0 = c$arg[88:71];

  assign opnd1_r_0 = c$arg[31:0];

  assign opnd0_r_0 = c$arg[63:32];

  assign status_out = result_0[38:32];

  assign result = result_0[31:0];


endmodule

