/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module alu
    ( // Inputs
      input [17:0] cntl
    , input [6:0] status_in
    , input [31:0] opnd0_r
    , input [31:0] opnd1_r

      // Outputs
    , output wire [6:0] status_out
    , output wire [31:0] result
    );
  wire [31:0] result_2;
  wire [0:0] bv;
  wire  c$bv_app_arg;
  wire [6:0] result_3;
  wire  c$app_arg;
  reg  result_4;
  wire [0:0] bv_0;
  reg  result_5;
  wire [0:0] bv_1;
  wire  c$app_arg_0;
  wire  c$app_arg_1;
  wire  c$app_arg_2;
  wire  c$app_arg_3;
  wire  c$app_arg_4;
  wire  c$bv_app_arg_0;
  wire  c$bv_app_arg_1;
  wire  c$app_arg_5;
  wire  c$case_alt;
  wire  c$case_alt_0;
  wire  c$app_arg_6;
  wire  c$case_alt_1;
  reg [0:0] c$app_arg_7;
  wire  c$app_arg_8;
  wire  c$case_alt_2;
  wire [32:0] result_6;
  wire  c$app_arg_9;
  wire  c$case_alt_3;
  reg  result_7;
  wire [0:0] bv_2;
  wire  c$case_alt_4;
  wire  c$bv_app_arg_2;
  wire  c$app_arg_10;
  wire  c$case_alt_5;
  wire  c$app_arg_11;
  wire [32:0] c$app_arg_12;
  wire  c$app_arg_13;
  wire [31:0] c$app_arg_14;
  wire  c$app_arg_15;
  wire [31:0] c$app_arg_16;
  wire  result_8;
  wire [0:0] bv_3;
  wire  c$bv_app_arg_3;
  wire [17:0] c$bv_app_arg_4;
  wire  c$app_arg_17;
  wire [6:0] c$app_arg_18;
  wire [32:0] result_9;
  // src/Alu/Internal.hs:59:1-5
  wire  carry;
  wire [32:0] result_10;
  wire [32:0] c$case_alt_6;
  wire [32:0] c$case_alt_7;
  wire [32:0] c$case_alt_8;
  wire [32:0] c$case_alt_9;
  wire [31:0] c$app_arg_19;
  wire [32:0] c$case_alt_10;
  wire [32:0] c$case_alt_11;
  wire [32:0] c$case_alt_12;
  wire [32:0] c$case_alt_13;
  wire [32:0] c$case_alt_14;
  wire [32:0] c$case_alt_15;
  wire [32:0] c$case_alt_16;
  wire [31:0] c$app_arg_20;
  wire [32:0] c$case_alt_17;
  wire [31:0] c$app_arg_21;
  wire signed [63:0] wild;
  wire signed [63:0] c$wild_app_arg;
  wire [63:0] w2;
  wire  c$app_arg_22;
  wire  c$app_arg_23;
  wire  c$app_arg_24;
  wire  c$app_arg_25;
  wire  c$app_arg_26;
  wire  c$app_arg_27;
  wire  c$app_arg_28;
  wire  c$app_arg_29;
  wire  c$app_arg_30;
  wire  c$app_arg_31;
  wire  c$app_arg_32;
  wire [17:0] c$app_arg_33;
  // src/Alu.hs:14:1-3
  wire  c$eta_app_arg;
  // src/Alu.hs:14:1-3
  wire [6:0] c$eta_app_arg_0;
  // src/Alu.hs:14:1-3
  wire [6:0] status_in_0;
  // src/Alu.hs:14:1-3
  wire  c$eta_app_arg_1;
  // src/Alu.hs:14:1-3
  wire [17:0] c$eta_app_arg_2;
  // src/Alu.hs:14:1-3
  wire [17:0] cntl_0;
  // src/Alu.hs:14:1-3
  wire [31:0] opnd1_r_0;
  // src/Alu.hs:14:1-3
  wire [31:0] opnd0_r_0;
  wire [88:0] ds;
  wire [31:0] result_sel_alt_t_res;
  wire [31:0] c$vec;
  wire [32:0] c$bv;
  wire [38:0] result_0;

  assign ds = {cntl,   status_in,   opnd0_r,
               opnd1_r};

  assign result_0 = {result_3,   result_2};

  assign c$vec = (32'b00000000000000000000000000000000);

  // map begin
  genvar i;
  generate
  for (i=0; i < 32; i = i + 1) begin : map
    wire [0:0] map_in;
    assign map_in = c$vec[i*1+:1];
    wire  map_out;
    assign map_out = map_in;


    assign result_sel_alt_t_res[i*1+:1] = map_out;
  end
  endgenerate
  // map end

  assign result_2 = (bv == 1'b1) ? result_sel_alt_t_res : (result_9[32-1 : 0]);

  assign bv = (c$bv_app_arg);

  assign c$bv_app_arg = c$eta_app_arg_2[8:8];

  assign result_3 = {c$app_arg_17,
                     c$app_arg_10,   c$app_arg_9,   c$app_arg_8,
                     c$app_arg_6,   c$app_arg_5,   c$app_arg};

  assign c$app_arg = result_8 ? c$case_alt_3 : result_4;

  always @(*) begin
    case(bv_0)
      1'b1 : result_4 = 1'b0;
      default : result_4 = result_5;
    endcase
  end

  assign bv_0 = (c$bv_app_arg_1);

  always @(*) begin
    case(bv_1)
      1'b1 : result_5 = ((c$app_arg_1 & c$app_arg_3) & c$case_alt_4) | ((c$app_arg_4 & c$app_arg_0) & c$app_arg_2);
      default : result_5 = ((c$app_arg_4 & c$app_arg_3) & c$app_arg_2) | ((c$app_arg_1 & c$app_arg_0) & c$case_alt_4);
    endcase
  end

  assign bv_1 = (c$bv_app_arg_0);

  assign c$app_arg_0 = ~ c$app_arg_3;

  assign c$app_arg_1 = ~ c$app_arg_4;

  assign c$app_arg_2 = ~ c$case_alt_4;

  assign c$app_arg_3 = opnd1_r_0[32-1 -: 1];

  assign c$app_arg_4 = opnd0_r_0[32-1 -: 1];

  assign c$bv_app_arg_0 = c$bv_app_arg_4[7:7];

  assign c$bv_app_arg_1 = c$bv_app_arg_4[4:4];

  assign c$app_arg_5 = result_8 ? c$case_alt : c$case_alt_0;

  assign c$case_alt = c$app_arg_18[5:5];

  assign c$case_alt_0 = result_9[31:31];

  assign c$app_arg_6 = result_8 ? c$case_alt_1 : ((c$app_arg_7));

  assign c$case_alt_1 = c$app_arg_18[4:4];

  always @(*) begin
    case(result_6)
      33'b000000000000000000000000000000000 : c$app_arg_7 = 1'b1;
      default : c$app_arg_7 = 1'b0;
    endcase
  end

  assign c$bv = (result_6);

  assign c$app_arg_8 = result_8 ? c$case_alt_2 : (~ (^ (((c$bv[7 : 0])))));

  assign c$case_alt_2 = c$app_arg_18[3:3];

  assign result_6 = ((result_9));

  assign c$app_arg_9 = result_8 ? c$case_alt_3 : result_7;

  assign c$case_alt_3 = c$app_arg_18[2:2];

  always @(*) begin
    case(bv_2)
      1'b1 : result_7 = 1'b0;
      default : result_7 = c$case_alt_4;
    endcase
  end

  assign bv_2 = (c$bv_app_arg_2);

  assign c$case_alt_4 = result_9[33-1 -: 1];

  assign c$bv_app_arg_2 = c$bv_app_arg_4[5:5];

  assign c$app_arg_10 = result_8 ? c$case_alt_5 : ((c$app_arg_15 ^ c$app_arg_13) ^ c$app_arg_11);

  assign c$case_alt_5 = c$app_arg_18[1:1];

  assign c$app_arg_11 = c$app_arg_12[28:28];

  // reverse begin
  genvar i_0;
  generate
  for (i_0 = 0; i_0 < 33; i_0 = i_0 + 1) begin : reverse
    assign c$app_arg_12[(33 - 1 - i_0)*1+:1] = result_9[i_0*1+:1];
  end
  endgenerate
  // reverse end

  assign c$app_arg_13 = c$app_arg_14[27:27];

  // reverse begin
  genvar i_1;
  generate
  for (i_1 = 0; i_1 < 32; i_1 = i_1 + 1) begin : reverse_0
    assign c$app_arg_14[(32 - 1 - i_1)*1+:1] = opnd1_r_0[i_1*1+:1];
  end
  endgenerate
  // reverse end

  assign c$app_arg_15 = c$app_arg_16[27:27];

  // reverse begin
  genvar i_2;
  generate
  for (i_2 = 0; i_2 < 32; i_2 = i_2 + 1) begin : reverse_1
    assign c$app_arg_16[(32 - 1 - i_2)*1+:1] = opnd0_r_0[i_2*1+:1];
  end
  endgenerate
  // reverse end

  assign result_8 = bv_3 == 1'b1;

  assign bv_3 = (c$bv_app_arg_3);

  assign c$bv_app_arg_3 = c$bv_app_arg_4[6:6];

  // reverse begin
  genvar i_3;
  generate
  for (i_3 = 0; i_3 < 18; i_3 = i_3 + 1) begin : reverse_2
    assign c$bv_app_arg_4[(18 - 1 - i_3)*1+:1] = cntl_0[i_3*1+:1];
  end
  endgenerate
  // reverse end

  assign c$app_arg_17 = c$app_arg_18[0:0];

  // reverse begin
  genvar i_4;
  generate
  for (i_4 = 0; i_4 < 7; i_4 = i_4 + 1) begin : reverse_3
    assign c$app_arg_18[(7 - 1 - i_4)*1+:1] = status_in_0[i_4*1+:1];
  end
  endgenerate
  // reverse end

  assign result_9 = (result_10);

  assign carry = c$eta_app_arg_1 & c$eta_app_arg;

  assign result_10 = (1'b1 == c$app_arg_32) ? c$case_alt_6 : c$case_alt_7;

  assign c$case_alt_6 = (((opnd0_r_0))) + c$app_arg_19;

  assign c$case_alt_7 = (1'b1 == c$app_arg_31) ? c$case_alt_8 : c$case_alt_9;

  assign c$case_alt_8 = (((opnd0_r_0))) - c$app_arg_19;

  assign c$case_alt_9 = (1'b1 == c$app_arg_30) ? ({1'b0,((((opnd0_r_0))) & (((opnd1_r_0))))}) : c$case_alt_10;

  assign c$app_arg_19 = (((opnd1_r_0))) + ({31'b0000000000000000000000000000000,((carry))});

  assign c$case_alt_10 = (1'b1 == c$app_arg_29) ? ({1'b0,((((opnd0_r_0))) | (((opnd1_r_0))))}) : c$case_alt_11;

  assign c$case_alt_11 = (1'b1 == c$app_arg_28) ? ({1'b0,((((opnd0_r_0))) ^ (((opnd1_r_0))))}) : c$case_alt_12;

  assign c$case_alt_12 = (1'b1 == c$app_arg_27) ? ({1'b0,((((opnd0_r_0))) * (((opnd1_r_0))))}) : c$case_alt_13;

  assign c$case_alt_13 = (1'b1 == c$app_arg_26) ? ({1'b0,((((opnd0_r_0))) << wild)}) : c$case_alt_14;

  assign c$case_alt_14 = (1'b1 == c$app_arg_25) ? ({1'b0,((((opnd0_r_0))) >> wild)}) : c$case_alt_15;

  assign c$case_alt_15 = (1'b1 == c$app_arg_24) ? ({1'b0,c$app_arg_20}) : c$case_alt_16;

  assign c$case_alt_16 = (1'b1 == c$app_arg_23) ? ({1'b0,c$app_arg_21}) : c$case_alt_17;

  // rotateL begin
  wire [2*32-1:0] bv_4;
  assign bv_4 = {(((opnd0_r_0))),(((opnd0_r_0)))} << (wild % 32);
  assign c$app_arg_20 = bv_4[2*32-1 : 32];
  // rotateL end

  assign c$case_alt_17 = (1'b1 == c$app_arg_22) ? ({1'b0,((((opnd0_r_0))) / (((opnd1_r_0))))}) : ({33 {1'bx}});

  // rotateR begin
  wire [2*32-1:0] bv_5;
  assign bv_5 = {(((opnd0_r_0))),(((opnd0_r_0)))} >> (wild % 32);
  assign c$app_arg_21 = bv_5[32-1 : 0];
  // rotateR end

  assign wild = $signed(c$wild_app_arg);

  assign c$wild_app_arg = $unsigned(w2[0+:64]);

  assign w2 = {32'b00000000000000000000000000000000,(((opnd1_r_0)))};

  assign c$app_arg_22 = c$app_arg_33[11:11];

  assign c$app_arg_23 = c$app_arg_33[0:0];

  assign c$app_arg_24 = c$app_arg_33[1:1];

  assign c$app_arg_25 = c$app_arg_33[2:2];

  assign c$app_arg_26 = c$app_arg_33[3:3];

  assign c$app_arg_27 = c$app_arg_33[12:12];

  assign c$app_arg_28 = c$app_arg_33[13:13];

  assign c$app_arg_29 = c$app_arg_33[14:14];

  assign c$app_arg_30 = c$app_arg_33[15:15];

  assign c$app_arg_31 = c$app_arg_33[7:7];

  assign c$app_arg_32 = c$app_arg_33[16:16];

  // reverse begin
  genvar i_5;
  generate
  for (i_5 = 0; i_5 < 18; i_5 = i_5 + 1) begin : reverse_4
    assign c$app_arg_33[(18 - 1 - i_5)*1+:1] = cntl_0[i_5*1+:1];
  end
  endgenerate
  // reverse end

  assign c$eta_app_arg = c$eta_app_arg_0[2:2];

  // reverse begin
  genvar i_6;
  generate
  for (i_6 = 0; i_6 < 7; i_6 = i_6 + 1) begin : reverse_5
    assign c$eta_app_arg_0[(7 - 1 - i_6)*1+:1] = status_in_0[i_6*1+:1];
  end
  endgenerate
  // reverse end

  assign status_in_0 = ds[70:64];

  assign c$eta_app_arg_1 = c$eta_app_arg_2[10:10];

  // reverse begin
  genvar i_7;
  generate
  for (i_7 = 0; i_7 < 18; i_7 = i_7 + 1) begin : reverse_6
    assign c$eta_app_arg_2[(18 - 1 - i_7)*1+:1] = cntl_0[i_7*1+:1];
  end
  endgenerate
  // reverse end

  assign cntl_0 = ds[88:71];

  assign opnd1_r_0 = ds[31:0];

  assign opnd0_r_0 = ds[63:32];

  assign status_out = result_0[38:32];

  assign result = result_0[31:0];


endmodule

