#!/usr/bin/env python3

import argparse
import subprocess

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="proof_statement",
        description="generate a tiny86 proof statement",
    )

    parser.add_argument("-w", '--witness')

    subprocess.run(["sv-compositor"])
