// this file was generated by ./codegen/tbgen
// do NOT edit it by hand
module decode_hint_tb();
reg clk, reset;
reg [31:0] current_vec, error_count;
reg [139:0] test_vectors [127:0];
reg [71:0] raw_hint;
reg [0:0] exp_valid_hint;
wire [0:0] valid_hint;
reg [1:0] exp_mask;
wire [1:0] mask;
reg [0:0] exp_is_write;
wire [0:0] is_write;
reg [31:0] exp_address;
wire [31:0] address;
reg [31:0] exp_data;
wire [31:0] data;
decode_hint dut(
.raw_hint(raw_hint),
.valid_hint(valid_hint),
.mask(mask),
.is_write(is_write),
.address(address),
.data(data)
);
always
  begin
    clk = 1; #5; clk = 0; #5;
  end
initial
  begin
    $dumpfile("decode_hint.tb.vcd");
    $dumpvars(0, decode_hint_tb);
    $readmemb("decode_hint.tv", test_vectors);
    current_vec = 0; error_count = 0;
    reset = 1; #10; reset = 0;
  end
always @(posedge clk)
  begin
    #1; { raw_hint, exp_valid_hint, exp_mask, exp_is_write, exp_address, exp_data } = test_vectors[current_vec];
  end
always @(negedge clk)
  begin
    if (~reset) begin
      if (exp_valid_hint === valid_hint || exp_valid_hint === 1'bx) begin
  $display("TBGEN-PASS decode_hint:%0d valid_hint", current_vec);
end else begin
  $display("TBGEN-FAIL decode_hint:%0d expected valid_hint to be 0x%h, was 0x%h", current_vec, exp_valid_hint, valid_hint);
  error_count = error_count + 1;
end

if (exp_mask === mask || exp_mask === 2'bx) begin
  $display("TBGEN-PASS decode_hint:%0d mask", current_vec);
end else begin
  $display("TBGEN-FAIL decode_hint:%0d expected mask to be 0x%h, was 0x%h", current_vec, exp_mask, mask);
  error_count = error_count + 1;
end

if (exp_is_write === is_write || exp_is_write === 1'bx) begin
  $display("TBGEN-PASS decode_hint:%0d is_write", current_vec);
end else begin
  $display("TBGEN-FAIL decode_hint:%0d expected is_write to be 0x%h, was 0x%h", current_vec, exp_is_write, is_write);
  error_count = error_count + 1;
end

if (exp_address === address || exp_address === 32'bx) begin
  $display("TBGEN-PASS decode_hint:%0d address", current_vec);
end else begin
  $display("TBGEN-FAIL decode_hint:%0d expected address to be 0x%h, was 0x%h", current_vec, exp_address, address);
  error_count = error_count + 1;
end

if (exp_data === data || exp_data === 32'bx) begin
  $display("TBGEN-PASS decode_hint:%0d data", current_vec);
end else begin
  $display("TBGEN-FAIL decode_hint:%0d expected data to be 0x%h, was 0x%h", current_vec, exp_data, data);
  error_count = error_count + 1;
end

      current_vec = current_vec + 1;

      if (test_vectors[current_vec] === 140'bx) begin
        $display("TBGEN-DONE decode_hint %0d errors=%0d", current_vec, error_count);
        $finish;
      end
    end
  end
endmodule
