// this file was generated by ./codegen/tbgen on 2021-04-09 15:27:42 -0400
// do NOT edit it by hand
module fetch_tb();
reg clk, reset;
reg [31:0] current_vec, error_count;
reg [1119:0] test_vectors [127:0];
reg [559:0] step;
reg [95:0] exp_raw_instr;
wire [95:0] raw_instr;
reg [31:0] exp_eax;
wire [31:0] eax;
reg [31:0] exp_ebx;
wire [31:0] ebx;
reg [31:0] exp_ecx;
wire [31:0] ecx;
reg [31:0] exp_edx;
wire [31:0] edx;
reg [31:0] exp_esi;
wire [31:0] esi;
reg [31:0] exp_edi;
wire [31:0] edi;
reg [31:0] exp_esp;
wire [31:0] esp;
reg [31:0] exp_ebp;
wire [31:0] ebp;
reg [31:0] exp_eip;
wire [31:0] eip;
reg [31:0] exp_eflags;
wire [31:0] eflags;
reg [71:0] exp_raw_hint1;
wire [71:0] raw_hint1;
reg [71:0] exp_raw_hint2;
wire [71:0] raw_hint2;
fetch dut(
.step(step),
.raw_instr(raw_instr),
.eax(eax),
.ebx(ebx),
.ecx(ecx),
.edx(edx),
.esi(esi),
.edi(edi),
.esp(esp),
.ebp(ebp),
.eip(eip),
.eflags(eflags),
.raw_hint1(raw_hint1),
.raw_hint2(raw_hint2)
);
always
  begin
    clk = 1; #5; clk = 0; #5;
  end
initial
  begin
    $dumpfile("fetch.tb.vcd");
    $dumpvars(0, fetch_tb);
    $readmemb("fetch.tv", test_vectors);
    current_vec = 0; error_count = 0;
    reset = 1; #10; reset = 0;
  end
always @(posedge clk)
  begin
    #1; { step, exp_raw_instr, exp_eax, exp_ebx, exp_ecx, exp_edx, exp_esi, exp_edi, exp_esp, exp_ebp, exp_eip, exp_eflags, exp_raw_hint1, exp_raw_hint2 } = test_vectors[current_vec];
  end
always @(negedge clk)
  begin
    if (~reset) begin
      if (exp_raw_instr === raw_instr || exp_raw_instr === 96'bx) begin
  $display("TBGEN-PASS fetch:%0d raw_instr", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected raw_instr to be 0x%h, was 0x%h", current_vec, exp_raw_instr, raw_instr);
  error_count = error_count + 1;
end

if (exp_eax === eax || exp_eax === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d eax", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected eax to be 0x%h, was 0x%h", current_vec, exp_eax, eax);
  error_count = error_count + 1;
end

if (exp_ebx === ebx || exp_ebx === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d ebx", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected ebx to be 0x%h, was 0x%h", current_vec, exp_ebx, ebx);
  error_count = error_count + 1;
end

if (exp_ecx === ecx || exp_ecx === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d ecx", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected ecx to be 0x%h, was 0x%h", current_vec, exp_ecx, ecx);
  error_count = error_count + 1;
end

if (exp_edx === edx || exp_edx === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d edx", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected edx to be 0x%h, was 0x%h", current_vec, exp_edx, edx);
  error_count = error_count + 1;
end

if (exp_esi === esi || exp_esi === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d esi", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected esi to be 0x%h, was 0x%h", current_vec, exp_esi, esi);
  error_count = error_count + 1;
end

if (exp_edi === edi || exp_edi === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d edi", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected edi to be 0x%h, was 0x%h", current_vec, exp_edi, edi);
  error_count = error_count + 1;
end

if (exp_esp === esp || exp_esp === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d esp", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected esp to be 0x%h, was 0x%h", current_vec, exp_esp, esp);
  error_count = error_count + 1;
end

if (exp_ebp === ebp || exp_ebp === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d ebp", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected ebp to be 0x%h, was 0x%h", current_vec, exp_ebp, ebp);
  error_count = error_count + 1;
end

if (exp_eip === eip || exp_eip === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d eip", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected eip to be 0x%h, was 0x%h", current_vec, exp_eip, eip);
  error_count = error_count + 1;
end

if (exp_eflags === eflags || exp_eflags === 32'bx) begin
  $display("TBGEN-PASS fetch:%0d eflags", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected eflags to be 0x%h, was 0x%h", current_vec, exp_eflags, eflags);
  error_count = error_count + 1;
end

if (exp_raw_hint1 === raw_hint1 || exp_raw_hint1 === 72'bx) begin
  $display("TBGEN-PASS fetch:%0d raw_hint1", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected raw_hint1 to be 0x%h, was 0x%h", current_vec, exp_raw_hint1, raw_hint1);
  error_count = error_count + 1;
end

if (exp_raw_hint2 === raw_hint2 || exp_raw_hint2 === 72'bx) begin
  $display("TBGEN-PASS fetch:%0d raw_hint2", current_vec);
end else begin
  $display("TBGEN-FAIL fetch:%0d expected raw_hint2 to be 0x%h, was 0x%h", current_vec, exp_raw_hint2, raw_hint2);
  error_count = error_count + 1;
end

      current_vec = current_vec + 1;

      if (test_vectors[current_vec] === 1120'bx) begin
        $display("TBGEN-DONE fetch %0d errors=%0d", current_vec, error_count);
        $finish;
      end
    end
  end
endmodule
