#!/usr/bin/env ruby

# run-tests: collect all .vvps and run each, parsing the output of each run
# produce output in TAP format

require_relative "./codegen/common"

def find_vvps
  Dir["*.tb.vvp"]
end

vvps = find_vvps
barf "no testbenches found; run make?" if vvps.empty?
verbose "discovered #{vvps.size} tests: #{vvps}"

puts "1..#{vvps.size}"

vvps.each_with_index do |vvp, i|
  lines = `vvp #{vvp} -lxt2`.split "\n"
  done = lines.find { |l| l.start_with? "TBGEN-DONE" }.split
  testcase = done[1]
  ntests = done[2].to_i
  nerrors = done[3].split("=")[1].to_i

  if nerrors.zero?
    puts "ok #{i + 1} #{testcase} ran #{ntests} internal tests"
  else
    puts "not ok #{i + 1} #{testcase} ran #{ntests} internal tests, #{nerrors} failed"
    exit 1
  end

  verbose ntests
  verbose nerrors
end
